import type { Metadata } from "next";
import "./globals.css";
import { michelin, notoSans } from "./fonts";

export const metadata: Metadata = {
  title: "Michelin Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${michelin.variable} ${notoSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
