import type { Metadata, Viewport } from "next";
import "./globals.css";
import "./michelin-poc.css";
import { michelin, notoSans } from "./fonts";

export const metadata: Metadata = {
  title: "Michelin Pulse",
  description: "Generated by create next app",
};

// viewport-fit=cover : laisse le contenu s'étendre derrière l'encoche/Dynamic
// Island des iPhone (sinon env(safe-area-inset-*) reste toujours à 0).
export const viewport: Viewport = {
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`${michelin.variable} ${notoSans.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
